name: xray_docker_xhttp_reality

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 */2 * *'  # UTC 21:00  UTC+8 05:00
  push:
    paths:
      - 'xhttp_reality/Dockerfile'
      - '.github/workflows/xray_docker_xhttp_reality.yml'
      - 'xhttp_reality/entrypoint.sh'
      - 'xhttp_reality/config.json'
      - 'xhttp_reality/VERSION'
  pull_request:
    paths:
      - 'xhttp_reality/Dockerfile'
      - '.github/workflows/xray_docker_xhttp_reality.yml'
      - 'xhttp_reality/entrypoint.sh'
      - 'xhttp_reality/config.json'
      - 'xhttp_reality/VERSION'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract first line of commit message
        shell: bash
        run: |
          VERSION=$(cat xhttp_reality/VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get latest Xray-core version (including pre-release)
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases | jq -r '.[0].tag_name')
          echo "XRAY_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./xhttp_reality
          file: ./xhttp_reality/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: |
            wulabing/xray_docker_xhttp_reality:${{env.VERSION}}-ubuntu-22.04-xray-${{env.XRAY_VERSION}}
            wulabing/xray_docker_xhttp_reality:latest
          push: true
